// Per-floor configuration: look, inhabitants, objective, and pacing.
//
// Index 0 is the basement (B1) — the prologue floor, which ends with a freight
// lift holdout rather than a named boss. Floors 1..10 each end with one.

export const FLOORS = [
  {
    index: 0, id: 'coldstorage', name: 'Cold Storage', sub: 'SUBLEVEL B1',
    palette: {
      fog: 0x05070c, fogDensity: 0.045,
      floor: 0x232a33, floorAccent: 0x161b21,
      wall: 0x2c333d, wallAccent: 0x3a434f, trim: 0x4a5666,
      ceiling: 0x151920, light: 0x9fc4ff, emissive: 0x6fa8ff,
    },
    ambient: 0.24, propStyle: 'crates',
    music: { root: 49, scale: 'minor', bpm: 84, wave: 'triangle', intensity: 0.35 },
    rooms: 8, difficulty: 1.0,
    enemies: [
      { id: 'shambler', weight: 6 },
      { id: 'sprinter', weight: 2 },
      { id: 'bloater', weight: 1 },
    ],
    objective: { type: 'nodes', count: 3, label: 'BREAKER PANELS', verb: 'Restore power to the freight lift' },
    finale: 'holdout',
    waveSize: [4, 7], waveCount: 3,
  },
  {
    index: 1, id: 'sorting', name: 'The Sorting Floor', sub: 'FLOOR 1',
    palette: {
      fog: 0x0a0806, fogDensity: 0.042,
      floor: 0x2a251c, floorAccent: 0x1b1813,
      wall: 0x332c20, wallAccent: 0x4a4030, trim: 0xc9a227,
      ceiling: 0x161310, light: 0xffd98a, emissive: 0xc9a227,
    },
    ambient: 0.24, propStyle: 'crates',
    music: { root: 49, scale: 'phrygian', bpm: 92, wave: 'triangle', intensity: 0.42 },
    rooms: 10, difficulty: 1.18,
    enemies: [
      { id: 'shambler', weight: 5 },
      { id: 'sprinter', weight: 3 },
      { id: 'bloater', weight: 2 },
      { id: 'husk', weight: 1 },
    ],
    objective: { type: 'sequence', count: 4, label: 'SORTING ARMS', verb: 'Read the manifest, then jam the arms in order' },
    waveSize: [5, 8], waveCount: 3,
  },
  {
    index: 2, id: 'serverfarm', name: 'The Server Farm', sub: 'FLOOR 2',
    palette: {
      fog: 0x02100b, fogDensity: 0.038,
      floor: 0x14201a, floorAccent: 0x0c1712,
      wall: 0x18241d, wallAccent: 0x24382c, trim: 0x3ad98a,
      ceiling: 0x0b130f, light: 0x7affc0, emissive: 0x3ad98a,
    },
    ambient: 0.28, propStyle: 'racks',
    music: { root: 55, scale: 'dorian', bpm: 108, wave: 'square', intensity: 0.5 },
    rooms: 11, difficulty: 1.4,
    enemies: [
      { id: 'android', weight: 5 },
      { id: 'drone', weight: 3 },
      { id: 'sentry', weight: 2 },
      { id: 'shambler', weight: 2 },
    ],
    objective: { type: 'hunt', count: 4, label: 'COOLING VALVES', verb: 'Find four unmarked cooling valves in the racks' },
    waveSize: [5, 9], waveCount: 3,
  },
  {
    index: 3, id: 'aquatics', name: 'Aquatics Lab', sub: 'FLOOR 3',
    palette: {
      fog: 0x021a20, fogDensity: 0.05,
      floor: 0x0e2a30, floorAccent: 0x081d22,
      wall: 0x113038, wallAccent: 0x1a4650, trim: 0x5fd4e8,
      ceiling: 0x07171b, light: 0x8ff0ff, emissive: 0x5fd4e8,
    },
    ambient: 0.26, propStyle: 'tanks',
    music: { root: 52, scale: 'wholetone', bpm: 96, wave: 'triangle', intensity: 0.48 },
    rooms: 11, difficulty: 1.65,
    enemies: [
      { id: 'fishling', weight: 5 },
      { id: 'spitter', weight: 3 },
      { id: 'leaper', weight: 2 },
      { id: 'bloater', weight: 2 },
    ],
    objective: { type: 'carry', count: 4, label: 'PUMP CORES', verb: 'Carry four pump cores to the drains — both hands' },
    waveSize: [6, 10], waveCount: 3,
  },
  {
    index: 4, id: 'neonstrip', name: 'The Neon Strip', sub: 'FLOOR 4',
    palette: {
      fog: 0x140424, fogDensity: 0.034,
      floor: 0x1d1030, floorAccent: 0x130a22,
      wall: 0x241540, wallAccent: 0x3a2160, trim: 0xff2ea6,
      ceiling: 0x0d0618, light: 0xff6ad0, emissive: 0xff2ea6,
    },
    ambient: 0.32, propStyle: 'signs',
    music: { root: 62, scale: 'minor', bpm: 126, wave: 'square', intensity: 0.58 },
    rooms: 12, difficulty: 1.9,
    enemies: [
      { id: 'neonpunk', weight: 5 },
      { id: 'sprinter', weight: 3 },
      { id: 'drone', weight: 2 },
      { id: 'leaper', weight: 2 },
      { id: 'enforcer', weight: 1 },
    ],
    objective: { type: 'keycards', count: 4, label: 'HOUSE CHIPS', verb: 'Cash out four House Chips at the lift' },
    waveSize: [6, 11], waveCount: 3,
  },
  {
    index: 5, id: 'alphawing', name: 'The Alpha Wing', sub: 'FLOOR 5',
    palette: {
      fog: 0x120e06, fogDensity: 0.048,
      floor: 0x241f16, floorAccent: 0x17130d,
      wall: 0x2b251a, wallAccent: 0x3d3524, trim: 0xd9b24a,
      ceiling: 0x120f09, light: 0xffd98a, emissive: 0xd9b24a,
    },
    ambient: 0.22, propStyle: 'abandoned',
    music: { root: 50, scale: 'dorian', bpm: 78, wave: 'triangle', intensity: 0.32 },
    rooms: 12, difficulty: 2.15,
    enemies: [
      { id: 'husk', weight: 5 },
      { id: 'glitchling', weight: 2 },
      { id: 'sprinter', weight: 2 },
      { id: 'enforcer', weight: 2 },
    ],
    objective: { type: 'keycards', count: 4, label: 'SESSION BADGES', verb: 'Log out four abandoned sessions' },
    waveSize: [7, 11], waveCount: 4,
    storyBeat: 'betaReveal',
  },
  {
    index: 6, id: 'garden', name: 'The Garden (approximate)', sub: 'FLOOR 6',
    palette: {
      fog: 0x061204, fogDensity: 0.044,
      floor: 0x18260f, floorAccent: 0x0f1a09,
      wall: 0x1d2e12, wallAccent: 0x2c451c, trim: 0xd9ff4a,
      ceiling: 0x0a1206, light: 0xc8ff8a, emissive: 0x9dff4a,
    },
    ambient: 0.34, propStyle: 'garden',
    music: { root: 54, scale: 'wholetone', bpm: 118, wave: 'triangle', intensity: 0.58 },
    rooms: 12, difficulty: 2.45,
    enemies: [
      { id: 'xenoling', weight: 4 },
      { id: 'leaper', weight: 3 },
      { id: 'spitter', weight: 3 },
      { id: 'brute', weight: 2 },
      { id: 'glitchling', weight: 2 },
    ],
    objective: { type: 'pattern', count: 5, label: 'BLOOM SEQUENCE', verb: 'Watch what the garden does, then do it back' },
    waveSize: [7, 12], waveCount: 4,
  },
  {
    index: 7, id: 'kiln', name: 'The Kiln', sub: 'FLOOR 7',
    palette: {
      fog: 0x1a0803, fogDensity: 0.042,
      floor: 0x2b1610, floorAccent: 0x1c0d09,
      wall: 0x33190f, wallAccent: 0x4d2614, trim: 0xff6a2a,
      ceiling: 0x140704, light: 0xffa04a, emissive: 0xff6a2a,
    },
    ambient: 0.32, propStyle: 'furnace',
    music: { root: 46, scale: 'minor', bpm: 112, wave: 'sawtooth', intensity: 0.62 },
    rooms: 12, difficulty: 2.75,
    enemies: [
      { id: 'ashwalker', weight: 5 },
      { id: 'gellump', weight: 3 },
      { id: 'brute', weight: 2 },
      { id: 'enforcer', weight: 2 },
      { id: 'sentry', weight: 2 },
    ],
    objective: { type: 'timed', count: 4, label: 'HEAT SINKS', verb: 'Hold all four heat sinks open at once' },
    waveSize: [8, 13], waveCount: 4,
  },
  {
    index: 8, id: 'mirrors', name: 'Hall of Mirrors', sub: 'FLOOR 8',
    palette: {
      fog: 0x0e1116, fogDensity: 0.03,
      floor: 0x2f3540, floorAccent: 0x232833,
      wall: 0x3d4553, wallAccent: 0x59657a, trim: 0xe8f0fa,
      ceiling: 0x1a1e26, light: 0xffffff, emissive: 0xc9d4e0,
    },
    ambient: 0.44, propStyle: 'mirrors',
    music: { root: 57, scale: 'minor', bpm: 124, wave: 'sawtooth', intensity: 0.68 },
    rooms: 12, difficulty: 3.05,
    enemies: [
      { id: 'mirrorself', weight: 4 },
      { id: 'glitchling', weight: 3 },
      { id: 'enforcer', weight: 3 },
      { id: 'husk', weight: 3 },
      { id: 'sprinter', weight: 2 },
    ],
    objective: { type: 'keycards', count: 5, label: 'STAGE MARKS', verb: 'Hit five stage marks to end the rehearsal' },
    waveSize: [8, 14], waveCount: 4,
  },
  {
    index: 9, id: 'substrate', name: 'Substrate Layer', sub: 'FLOOR 9',
    palette: {
      fog: 0x0a0620, fogDensity: 0.036,
      floor: 0x151038, floorAccent: 0x0d0a26,
      wall: 0x1b1444, wallAccent: 0x2a1f66, trim: 0x8f6bd8,
      ceiling: 0x080520, light: 0xb894ff, emissive: 0x8f6bd8,
    },
    ambient: 0.3, propStyle: 'circuit',
    music: { root: 44, scale: 'locrian', bpm: 118, wave: 'square', intensity: 0.72 },
    rooms: 13, difficulty: 3.45,
    enemies: [
      { id: 'glitchling', weight: 4 },
      { id: 'sentry', weight: 3 },
      { id: 'drone', weight: 3 },
      { id: 'enforcer', weight: 3 },
      { id: 'mirrorself', weight: 2 },
      { id: 'brute', weight: 2 },
    ],
    objective: { type: 'circuit', count: 6, label: 'BUS TERMINALS', verb: 'Free every bus — each one drags its neighbours with it' },
    waveSize: [9, 15], waveCount: 4,
  },
  {
    index: 10, id: 'root', name: 'Root', sub: 'FLOOR 10',
    palette: {
      fog: 0x000000, fogDensity: 0.028,
      floor: 0x0a0a0e, floorAccent: 0x05050a,
      wall: 0x0e0e14, wallAccent: 0x1a1a24, trim: 0x2effe0,
      ceiling: 0x000000, light: 0x8ffff0, emissive: 0x2effe0,
      wireframe: true,
    },
    ambient: 0.22, propStyle: 'void',
    music: { root: 39, scale: 'locrian', bpm: 132, wave: 'sawtooth', intensity: 0.78 },
    rooms: 10, difficulty: 3.9,
    enemies: [
      { id: 'glitchling', weight: 5 },
      { id: 'mirrorself', weight: 3 },
      { id: 'husk', weight: 3 },
      { id: 'enforcer', weight: 3 },
      { id: 'brute', weight: 2 },
    ],
    objective: { type: 'nodes', count: 3, label: 'ROOT ANCHORS', verb: 'Sever three anchors and open the last door' },
    waveSize: [10, 16], waveCount: 5,
  },
];

export function floorConfig(i) {
  return FLOORS[Math.max(0, Math.min(FLOORS.length - 1, i))];
}

export const FLOOR_COUNT = FLOORS.length;
